export const GET_TRAINER_LIST = 'APP/TRAINER_LIST/GET_TRAINER_LIST';
export const GET_TRAINER_LIST_SUCCESS = 'APP/TRAINER_LIST/GET_TRAINER_LIST_SUCCESS';
export const GET_TRAINER_LIST_FAILURE = 'APP/TRAINER_LIST/GET_TRAINER_LIST_FAILURE';