export const GET_EXERCISES_AND_TRAINERS = 'APP/FITNES_CENTER/GET_EXERCISES_AND_TRAINERS';
export const GET_EXERCISES_AND_TRAINERS_SUCCESS = 'APP/FITNES_CENTER/GET_EXERCISES_AND_TRAINERS_SUCCESS';
export const GET_EXERCISES_AND_TRAINERS_FAILURE = 'APP/FITNES_CENTER/GET_EXERCISES_AND_TRAINERS_FAILURE';

