export const SET_USER_PROFILE = 'APP/FITNES_CENTER/SET_USER_PROFILE';
export const SET_USER_PROFILE_SUCCESS = 'APP/FITNES_CENTER/SET_USER_PROFILE_SUCCESS';
export const SET_USER_PROFILE_FAILURE = 'APP/FITNES_CENTER/SET_USER_PROFILE_FAILURE';
export const LOGOUT_PROFILE = 'APP/FITNES_CENTER/LOGOUT_PROFILE';
