export const GET_PAYMENTS = 'APP/FITNES_CENTER/GET_PAYMENTS';
export const GET_PAYMENTS_SUCCESS = 'APP/FITNES_CENTER/GET_PAYMENTS_SUCCESS';
export const GET_PAYMENTS_FAILURE = 'APP/FITNES_CENTER/GET_PAYMENTS_FAILURE';

