export const SET_USER_PROFILE_FOR_TRAINING = 'APP/FITNES_CENTER/SET_USER_PROFILE_FOR_TRAINING';
export const SET_USER_PROFILE_FOR_TRAINING_SUCCESS = 'APP/FITNES_CENTER/SET_USER_PROFILE_FOR_TRAINING_SUCCESS';
export const SET_USER_PROFILE_FOR_TRAINING_FAILURE = 'APP/FITNES_CENTER/SET_USER_PROFILE_FOR_TRAINING_FAILURE';
